# Generated by Django 5.0.6 on 2024-05-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_adddate_alter_event_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startDate']},
        ),
    ]
