# Generated by Django 5.0.6 on 2024-05-31 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='addDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
