# Generated by Django 5.0.6 on 2024-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_event_author_alter_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
