# Generated by Django 5.0.6 on 2024-06-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accepted',
        ),
    ]
