# Generated by Django 5.0.6 on 2024-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_event_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
