# Generated by Django 5.0.4 on 2024-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('firm', 'Firm')], default='firm', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('firm', 'Firm')], default='student', max_length=10),
        ),
    ]
