# Generated by Django 5.0.4 on 2024-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_firm_user_type_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nameFirm',
            field=models.CharField(default='Nokia', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='https://www.nokia.com/', max_length=100),
        ),
        migrations.DeleteModel(
            name='Firm',
        ),
    ]
