# Generated by Django 5.0.6 on 2024-06-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_event_picture'),
        ('main', '0018_alter_profile_course_alter_profile_faculty_and_more'),
    ]

    operations = [
    ]
