# Generated by Django 5.0.6 on 2024-06-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_20240604_2150'),
        ('main', '0019_merge_20240604_2307'),
    ]

    operations = [
    ]
