# Generated by Django 5.0.6 on 2024-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='user_icon.png', upload_to='profile_pictures'),
        ),
    ]
