# Generated by Django 5.0.6 on 2024-06-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_20240604_2347'),
        ('main', '0026_alter_event_picture'),
    ]

    operations = [
    ]
