# Generated by Django 5.0.6 on 2024-06-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_event_title'),
        ('main', '0028_bug'),
    ]

    operations = [
    ]
