# Generated by Django 5.0.4 on 2024-06-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_event_title'),
        ('main', '0029_merge_0028_alter_event_title_0028_bug'),
    ]

    operations = [
    ]
