# Generated by Django 5.0.6 on 2024-06-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_20240605_0328'),
        ('main', '0030_merge_20240609_2324'),
    ]

    operations = [
    ]
