# Generated by Django 5.0.4 on 2024-06-18 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_merge_20240611_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+48570099806'.", regex='^\\+48\\d{9}$')]),
        ),
    ]
